[package]
name = "simple_crud"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenvy = "0.15.7"
postgres = "0.19.7"
serde = "1.0.197"
serde_derive = "1.0.197"
serde_json = "1.0.115"
